export const VIETNAM_CITIES = [
  { value: 'hanoi', label: 'TP. Hà Nội' },
  { value: 'hcm', label: 'TP. Hồ Chí Minh' },
  { value: 'haiphong', label: 'TP. Hải Phòng' },
  { value: 'hue', label: 'TP. Huế' },
  { value: 'danang', label: 'TP. Đà Nẵng' },
  { value: 'cantho', label: 'TP. Cần Thơ' },
  { value: 'angiang', label: 'An Giang' },
  { value: 'bacninh', label: 'Bắc Ninh' },
  { value: 'camau', label: 'Cà Mau' },
  { value: 'caobang', label: 'Cao Bằng' },
  { value: 'daklak', label: 'Đắk Lắk' },
  { value: 'dienbien', label: 'Điện Biên' },
  { value: 'dongnai', label: 'Đồng Nai' },
  { value: 'dongthap', label: 'Đồng Tháp' },
  { value: 'gia-lai', label: 'Gia Lai' },
  { value: 'ha-tinh', label: 'Hà Tĩnh' },
  { value: 'hung-yen', label: 'Hưng Yên' },
  { value: 'khanh-hoa', label: 'Khánh Hòa' },
  { value: 'lai-chau', label: 'Lai Châu' },
  { value: 'lam-dong', label: 'Lâm Đồng' },
  { value: 'lang-son', label: 'Lạng Sơn' },
  { value: 'lao-cai', label: 'Lào Cai' },
  { value: 'nghe-an', label: 'Nghệ An' },
  { value: 'ninh-binh', label: 'Ninh Bình' },
  { value: 'phu-tho', label: 'Phú Thọ' },
  { value: 'quang-ngai', label: 'Quảng Ngãi' },
  { value: 'quang-ninh', label: 'Quảng Ninh' },
  { value: 'quang-tri', label: 'Quảng Trị' },
  { value: 'son-la', label: 'Sơn La' },
  { value: 'tay-ninh', label: 'Tây Ninh' },
  { value: 'thai-nguyen', label: 'Thái Nguyên' },
  { value: 'thanh-hoa', label: 'Thanh Hóa' },
  { value: 'tuyen-quang', label: 'Tuyên Quang' },
  { value: 'vinh-long', label: 'Vĩnh Long' }
];
