import { registerLocaleData } from '@angular/common';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import vi from '@angular/common/locales/vi';
import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideNzConfig } from 'ng-zorro-antd/core/config';
import { provideNzI18n, vi_VN } from 'ng-zorro-antd/i18n';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { routes } from './app.routes';

import {
  AppstoreOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  BarcodeOutline,
  BlockOutline,
  BorderInnerOutline,
  CalendarOutline,
  CaretDownOutline,
  CarOutline,
  CheckCircleOutline,
  CheckOutline,
  CloseCircleOutline,
  CodeSandboxOutline,
  CopyOutline,
  CreditCardOutline,
  CustomerServiceOutline,
  DashboardOutline,
  DashOutline,
  DeleteOutline,
  DeleteTwoTone,
  DeploymentUnitOutline,
  DollarOutline,
  DownloadOutline,
  DownOutline,
  EditOutline,
  EnterOutline,
  EnvironmentOutline,
  ExperimentOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FacebookOutline,
  FileExcelOutline,
  FileTextOutline,
  FilterOutline,
  FormatPainterOutline,
  GiftOutline,
  HeartFill,
  HeartOutline,
  HistoryOutline,
  HomeOutline,
  IdcardOutline,
  InboxOutline,
  LinkOutline,
  LoadingOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  MinusOutline,
  MinusSquareOutline,
  MoonOutline,
  PhoneOutline,
  PictureOutline,
  PlusCircleOutline,
  PlusOutline,
  PlusSquareOutline,
  ProfileOutline,
  QuestionCircleOutline,
  ReconciliationOutline,
  RestOutline,
  RightOutline,
  RocketOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  SaveOutline,
  ScissorOutline,
  SearchOutline,
  SendOutline,
  SettingOutline,
  ShoppingCartOutline,
  ShoppingOutline,
  SunOutline,
  SyncOutline,
  TagsOutline,
  TeamOutline,
  ThunderboltOutline,
  ToolOutline,
  TrademarkOutline,
  UndoOutline,
  UploadOutline,
  UserAddOutline,
  UserOutline,
  WalletOutline,
  WarningFill,
  WarningOutline
} from '@ant-design/icons-angular/icons';
import { maskingInterceptor } from './shared/interceptors/masking.interceptor';

const icons = [
  CheckCircleOutline,
  ShoppingCartOutline,
  DownOutline,
  ArrowLeftOutline,
  ShoppingOutline,
  HeartOutline,
  HeartFill,
  SearchOutline,
  PhoneOutline,
  MailOutline,
  SettingOutline,
  ToolOutline,
  ScissorOutline,
  AppstoreOutline,
  DashboardOutline,
  ExperimentOutline,
  DeleteTwoTone,
  DeleteOutline,
  UserOutline,
  LockOutline,
  EyeOutline,
  EyeInvisibleOutline,
  ProfileOutline,
  HistoryOutline,
  LogoutOutline,
  PlusCircleOutline,
  EditOutline,
  InboxOutline,
  MoonOutline,
  SunOutline,
  CustomerServiceOutline,
  FacebookOutline,
  EnvironmentOutline,
  MenuOutline,
  QuestionCircleOutline,
  SafetyCertificateOutline,
  ArrowRightOutline,
  SendOutline,
  BarcodeOutline,
  CarOutline,
  HomeOutline,
  CreditCardOutline,
  CalendarOutline,
  DollarOutline,
  CloseCircleOutline,
  FileTextOutline,
  WalletOutline,
  ArrowUpOutline,
  MenuUnfoldOutline,
  MenuFoldOutline,
  TeamOutline,
  PlusOutline,
  UploadOutline,
  LinkOutline,
  DashOutline,
  WarningOutline,
  WarningFill,
  MinusOutline,
  BlockOutline,
  BorderInnerOutline,
  FormatPainterOutline,
  DeploymentUnitOutline,
  TagsOutline,
  EnterOutline,
  PictureOutline,
  TrademarkOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  SyncOutline,
  LoadingOutline,
  FileExcelOutline,
  DownloadOutline,
  SaveOutline,
  CheckCircleOutline,
  CodeSandboxOutline,
  ReconciliationOutline,
  FilterOutline,
  RightOutline,
  CheckOutline,
  CaretDownOutline,
  SafetyOutline,
  CopyOutline,
  UndoOutline,
  ThunderboltOutline,
  LoginOutline, 
  GiftOutline,
  UserAddOutline,
  IdcardOutline,
  RocketOutline,
  RestOutline,
  LoadingOutline,
];

registerLocaleData(vi);

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withInMemoryScrolling({ scrollPositionRestoration: 'enabled' })),
    provideAnimationsAsync(),
    provideNzI18n(vi_VN),
    provideNzIcons(icons),
    importProvidersFrom(NzModalModule),
    provideHttpClient(withInterceptors([maskingInterceptor])),
  ]
};
